### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/spotify_assistant#20]
**Congratulations on finishing milestone 1!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

## 1. Team work contract

Good Job!

## 2. Create project structure for the python project (40 points)

- [x] The name of the repository doesn't follow the recommended conventions for python packages:  - **mechanics -1**

**Comment:** Name the repository after the python package, it is not necessary to include DSCI524 and group 9. This could be changed in the repository settings.

- [x] There isn't a `CONTRIBUTORS.md` file - **mechanics -5**

**Comment:** CONTRIBUTORS.md file is not included in the repository. You could use [this](https://github.com/ttimbers/convertempPy/blob/master/CONTRIBUTORS.md) as an example of what to include in this file.

## 3. Function specifications (20 points)

Good Job!

## 4. Manage issues (10 points)
- [x] There isn't a milestone created - **mechanics -1**

**Comments:** I would suggest breaking up your issues into smaller tasks. For example, including writing the function docstring in one issue and writing the code in another issue so that they can be separated in different milestones and be moved to "done" in the project board. Since all the tasks for a function are in one issue, milestone 1 is not complete. Also, make sure to include an assignees for every issue.

## 5. Specific expectations for this milestone are: (10 points)

Good Job!

## 6. Submission instructions (10 points)

Good Job!

**Comment by ChesterAiGo** [comment]
Hi Glenn,

First of all, on behalf of Group 9, we would like to express our appreciation for your time and efforts in grading our work.

We would like to inquire about the deduction made for "There isn't a CONTRIBUTORS.md file - mechanics -5" as stated in our grade report. We noticed that the Milestone 1 description on the course website (https://pages.github.ubc.ca/mds-2021-22/DSCI_524_collab-sw-dev_students/materials/assignments/milestone1.html) in Section 3, Point 4, states that "Once the projects have been created, edit the CONTRIBUTORS section in the README.md to add the contributor names (the students on the team)." We have included all the contributor names in the README.md, thus we believe that our project has satisfied this requirement. We kindly request that you review this matter and consider restoring the marks that were deducted.

Thank you for your time and consideration.

Sincerely,
Group 9

**Comment by Glenn032787** [comment]
Hey! I asked the instructors and they said that as it is best practice, they want you to include a CONTRIBUTOR.md file. As you mentioned it in the README, I will reduce the points by 2.5 only but make sure to include it in the next milestone.

**Comment by ChesterAiGo** [comment]
Thank you Glenn!
