### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/spotify_assistant#64]
> **Congratulations on finishing milestone 3!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.   
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

### 1. Write test cases and code iteratively
rubric={accuracy:20,quality:10,mechanics:10}

- [ ] There isn't documentation for test functions - **-5 quality**

Comments: Well done! Zero fails!

### 1. GitHub actions workflow for continuous integration
rubric={mechanics:10}

Well done!

### 2. GitHub actions workflow for continuous deployment
rubric={mechanics:10}

- [ ] The Python package downloaded from PyPi is not working - **-5 mechanics**

Comments:
-It is not noted that the dataset should be existing in the running directory.
-I could only successfully run the example in the ReadTheDocs.
-The script in 'README.md', the usage section, did not run and ended with the following error:

![Screen Shot 2023-02-05 at 7 28 14 AM](https://user-images.githubusercontent.com/86759356/216839771-d1420ad7-aa63-4a63-aab4-356d69466436.png)

### 3. Documentation
rubric={reasoning:10}

- [ ] There is no link on `GitHub` or in the `README.md` to ReadTheDocd - **-2 reasoning**
- [ ] The documentation lacks details - **-3 reasoning**

Comments: There is very limited documentation provided on the ReadTheDocs. It does only include one of the functions, with no explanation.

## 4. Specific expectations for this milestone 
rubric={mechanics:10}

Well done!

## 5. Submission instructions
rubric={mechanics:10}

Well done!

**Comment by chendaniely** [comment]
The example in the README should be fixed:

```python


credentials = {clientId:'xxxxxxxxxxxx', clientSecret: 'xxxxxxxxxxxx'} # original
credentials = {'clientId':'xxxxxxxxxxxx', 'clientSecret': 'xxxxxxxxxxxx'} # fixed
```
note the quotes around the keys of the dict.

that's why everything else errored.
